# Generated by Django 5.1.4 on 2025-01-10 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria_alter_organizacion_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='project_photos/', verbose_name='Foto')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(max_length=800000, verbose_name='Descripción del Compromiso')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
        ),
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de eje')),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.compromiso', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.compromiso', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='eje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eje', verbose_name='Eje'),
        ),
        migrations.DeleteModel(
            name='proyecto',
        ),
    ]
