# Generated by Django 5.1.4 on 2025-01-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compromiso_eje_alter_comentario_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
