# Generated by Django 5.1.4 on 2025-01-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organizacion_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('plazo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('direccion', models.URLField(blank=True, null=True)),
                ('medio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.medio')),
            ],
        ),
    ]
