# Generated by Django 5.1.4 on 2025-01-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medio_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='detalle',
            field=models.TextField(default='Sin detalle', max_length=80000, verbose_name='Detalle del Evento'),
        ),
    ]
