# Generated by Django 5.1.4 on 2025-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='detalle',
            field=models.TextField(default='Escribe el detalle del evento', max_length=80000, verbose_name='Detalle del Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(default='Sin dirección física', max_length=255),
        ),
    ]
