# Generated by Django 5.1.4 on 2025-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evento_url_alter_evento_detalle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha',
            new_name='fechainicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='hora',
        ),
        migrations.AddField(
            model_name='evento',
            name='fechafin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='horafin',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='evento',
            name='horainicio',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
