# Generated by Django 5.1.4 on 2025-01-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_fecha_evento_fechainicio_remove_evento_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromiso',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='compromiso',
            name='description',
        ),
        migrations.RemoveField(
            model_name='compromiso',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='compromiso',
            name='title',
        ),
        migrations.RemoveField(
            model_name='compromiso',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='compromiso',
            name='accion',
            field=models.TextField(blank=True, null=True, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='area_responsable',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área Responsable'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='avance',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de Avance'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='correo_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico de Contacto'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='estado_avance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado del Avance'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='estado_inicial',
            field=models.TextField(blank=True, null=True, verbose_name='Estado Inicial'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='otros_actores',
            field=models.TextField(blank=True, null=True, verbose_name='Otros Actores'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='problema',
            field=models.TextField(blank=True, null=True, verbose_name='Problema'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='relevancia',
            field=models.TextField(blank=True, null=True, verbose_name='Relevancia con los valores del Gobierno Abierto'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='responsables',
            field=models.TextField(blank=True, null=True, verbose_name='Responsables'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddField(
            model_name='compromiso',
            name='titulo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Título del Compromiso'),
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Hito')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado del Compromiso')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha Final')),
                ('avance', models.FloatField(default=0.0, verbose_name='Avance')),
                ('compromiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='core.compromiso')),
            ],
        ),
    ]
