# Generated by Django 5.1.4 on 2025-01-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_compromiso_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hito',
            name='evidencia',
            field=models.URLField(blank=True, verbose_name='Evidencia'),
        ),
    ]
