# Generated by Django 5.1.4 on 2025-01-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_photos/user.png', upload_to='user_photos/'),
        ),
    ]
